"""
mc_break.py -- Monte Carlo estimation of P(k) in Model M (Section 5).

Uniform random strokes x = (V0, phi) on Omega = (0, V_MAX] x [0, 2pi)
from the epsilon-separated opening configuration c0. Counts the number
of object balls pocketed per stroke. Writes incremental results so long
runs can be interrupted and resumed.

Usage:
    python3 mc_break.py                 # main run (default n=20000)
    python3 mc_break.py 100000          # bigger run
    python3 mc_break.py 4000 sens       # sensitivity grid, n per cell

Outputs:
    mc_results.json      counts and metadata (updated incrementally)
    mc_sensitivity.json  sensitivity grid results
    results_table.tex    LaTeX table of P(k) with 95% Wilson intervals
    fit_summary.txt      log-linear decay fit and extrapolation to k=21
"""

import json
import math
import os
import random
import sys
import time

import model_sim as M

V_MAX = 12.0
CHUNK = 200          # write results every CHUNK shots


def one_shot(v0, phi, eps=5e-4, A=None, e_ball=None):
    if A is not None:
        M.A = A
    if e_ball is not None:
        M.E_BALL = e_ball
    balls, cue = M.opening_rack(eps=eps)
    M.shoot(cue, v0, phi)
    sim = M.Simulator(balls)
    sim.run()
    # count pocketed OBJECT balls (exclude the cue ball)
    return sum(1 for _, name, _, _ in sim.pocketed if name != "cue")


def wilson(k, n, z=1.96):
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    den = 1 + z * z / n
    ctr = (p + z * z / (2 * n)) / den
    hw = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return (max(ctr - hw, 0.0), min(ctr + hw, 1.0))


def run_main(n_target, path="mc_results.json", seed=20260712):
    counts = {}
    n_done = 0
    if os.path.exists(path):
        d = json.load(open(path))
        counts = {int(k): v for k, v in d["counts"].items()}
        n_done = d["n"]
        seed = d["seed"] + n_done          # continue the stream
        print(f"resuming at n={n_done}")
    rng = random.Random(seed)
    t0 = time.time()
    while n_done < n_target:
        m = min(CHUNK, n_target - n_done)
        for _ in range(m):
            v0 = rng.uniform(1e-6, V_MAX)
            phi = rng.uniform(0, 2 * math.pi)
            k = one_shot(v0, phi)
            counts[k] = counts.get(k, 0) + 1
        n_done += m
        json.dump({"n": n_done, "seed": seed, "counts": counts,
                   "V_MAX": V_MAX, "A": M.A, "E_BALL": M.E_BALL,
                   "E_CUSH": M.E_CUSH, "RHO": M.RHO, "eps": 5e-4},
                  open(path, "w"), indent=1)
        rate = n_done / (time.time() - t0 + 1e-9)
        print(f"n={n_done}  rate={rate:.1f}/s  "
              f"dist={dict(sorted(counts.items()))}", flush=True)
    emit_table(path)
    emit_fit(path)


def run_sensitivity(n_cell, path="mc_sensitivity.json", seed=777):
    grid_A = (0.05, 0.10, 0.15)
    grid_e = (0.90, 0.95, 0.98)
    out = {}
    for a in grid_A:
        for e in grid_e:
            rng = random.Random(seed)
            counts = {}
            for _ in range(n_cell):
                v0 = rng.uniform(1e-6, V_MAX)
                phi = rng.uniform(0, 2 * math.pi)
                k = one_shot(v0, phi, A=a, e_ball=e)
                counts[k] = counts.get(k, 0) + 1
            out[f"A={a},e={e}"] = {"n": n_cell, "counts": counts}
            print(f"A={a} e={e}: {dict(sorted(counts.items()))}",
                  flush=True)
            json.dump(out, open(path, "w"), indent=1)
    # restore defaults
    M.A, M.E_BALL = 0.10, 0.95


def emit_table(path="mc_results.json", out="results_table.tex"):
    d = json.load(open(path))
    n = d["n"]
    counts = {int(k): v for k, v in d["counts"].items()}
    kmax = max(counts)
    lines = [
        "% generated by mc_break.py -- do not edit by hand",
        "\\begin{tabular}{rrll}",
        "\\toprule",
        "$k$ & count & $\\hat P(k)$ & 95\\% Wilson CI \\\\",
        "\\midrule",
    ]
    for k in range(0, kmax + 1):
        c = counts.get(k, 0)
        p = c / n
        lo, hi = wilson(c, n)
        lines.append(f"{k} & {c} & {p:.2e} & "
                     f"[{lo:.2e},\\,{hi:.2e}] \\\\")
    lines += ["\\bottomrule", "\\end{tabular}",
              f"% n = {n} strokes"]
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out}")


def emit_fit(path="mc_results.json", out="fit_summary.txt"):
    d = json.load(open(path))
    n = d["n"]
    counts = {int(k): v for k, v in d["counts"].items()}
    pts = [(k, c / n) for k, c in sorted(counts.items())
           if k >= 1 and c >= 5]
    lines = [f"n = {n}"]
    if len(pts) >= 3:
        xs = [k for k, _ in pts]
        ys = [math.log10(p) for _, p in pts]
        mx = sum(xs) / len(xs)
        my = sum(ys) / len(ys)
        b = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / \
            sum((x - mx) ** 2 for x in xs)
        a = my - b * mx
        p21 = 10 ** (a + b * 21)
        lines += [f"log-linear fit over k = {xs[0]}..{xs[-1]} "
                  f"(points with count >= 5):",
                  f"log10 P(k) = {a:.3f} + {b:.3f} k",
                  f"extrapolated P(21) ~ {p21:.2e}",
                  "NOTE: extrapolation is heuristic and conditional on "
                  "Conjecture 1; report it as such."]
    else:
        lines += ["not enough populated k values for a fit; "
                  "increase n"]
    open(out, "w").write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 20000
    if len(sys.argv) > 2 and sys.argv[2] == "sens":
        run_sensitivity(n)
    else:
        run_main(n)
